workflow:
  rules:
    # Disable merge request pipelines
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GH_PROJECT_PATH: "MatrixAI/${CI_PROJECT_NAME}"
  GH_PROJECT_URL: "https://${GITHUB_TOKEN}@github.com/${GH_PROJECT_PATH}.git"
  # Cache .npm
  NPM_CONFIG_CACHE: "${CI_PROJECT_DIR}/tmp/npm"
  # Prefer offline node module installation
  NPM_CONFIG_PREFER_OFFLINE: "true"

default:
  interruptible: true
  before_script:
    - mkdir -p "$CI_PROJECT_DIR/tmp"

# Cached directories shared between jobs & pipelines per-branch per-runner
cache:
  key: $CI_COMMIT_REF_SLUG
  # Preserve cache even if job fails
  when: 'always'
  paths:
    - ./tmp/npm/
    - ./.docusaurus

stages:
  - check       # Linting, unit tests
  - build       # Cross-platform library compilation, unit tests
  - integration # Cross-platform application bundling, integration tests, and pre-release
  - release     # Cross-platform distribution and deployment

image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner

check:lint:
  stage: check
  needs: []
  script:
    - >
      nix-shell --arg ci true --run $'
      npm run lint;
      '
  rules:
    # Runs on staging and feature commits
    - if: $CI_COMMIT_BRANCH =~ /^(?:feature.*|staging)$/
    # Manually run on commits other than master
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != 'master'
      when: manual

build:integration:
  stage: build
  needs: []
  variables:
    URL: 'https://testnet.polykey.com'
  script:
    - echo 'Perform static site generation'
    - >
      nix-shell --arg ci true --run $'
      npm run build;
      '
  artifacts:
    when: always
    paths:
      - ./public
  rules:
        # Runs on master and staging commits
    - if: $CI_COMMIT_BRANCH == 'staging'

build:release:
  stage: build
  needs: []
  variables:
    URL: 'https://mainnet.polykey.com'
  script:
    - echo 'Perform static site generation'
    - >
      nix-shell --arg ci true --run $'
      npm run build;
      '
  artifacts:
    when: always
    paths:
      - ./public
  rules:
        # Runs on master and staging commits
    - if: $CI_COMMIT_BRANCH =~ 'master'

build:merge:
  stage: build
  needs: []
  allow_failure: true
  script:
    # Required for `gh pr create`
    - git remote add upstream "$GH_PROJECT_URL"
    - >
      nix-shell --arg ci true --run $'
      gh pr create \
        --head staging \
        --base master \
        --title "ci: merge staging to master" \
        --body "This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful." \
        --assignee "@me" \
        --no-maintainer-edit \
        --repo "$GH_PROJECT_PATH" || true;
      printf "Pipeline Attempt on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
      | gh pr comment staging \
        --body-file - \
        --repo "$GH_PROJECT_PATH";
      '
  rules:
    # Runs on staging commits and ignores version commits
    - if: $CI_COMMIT_BRANCH == 'staging' && $CI_COMMIT_TITLE !~ /^[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/

integration:deployment:
  stage: integration
  needs:
    - check:lint
    - build:integration
  # Don't interrupt deploying job
  interruptible: false
  # Requires mutual exclusion
  resource_group: release:deployment
  environment:
    name: 'preview'
    deployment_tier: 'staging'
    url: 'https://testnet.polykey.com'
  script:
    - echo 'Perform service deployment for staging'
    - >
      nix-shell --arg ci true --run $'
      npm run deploy;
      '
  rules:
    # Runs on master commits
    - if: $CI_COMMIT_BRANCH == 'staging'

integration:merge:
  stage: integration
  needs:
    - build:merge
    - job: build:integration
      optional: true
    # - job: integration:windows
    #   optional: true
    # - job: integration:macos
    #   optional: true
  # Requires mutual exclusion
  resource_group: integration:merge
  allow_failure: true
  variables:
    # Ensure that CI/CD is fetching all commits
    # this is necessary to checkout origin/master
    # and to also merge origin/staging
    GIT_DEPTH: 0
  script:
    - >
      nix-shell --arg ci true --run $'
      printf "Pipeline Succeeded on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
      | gh pr comment staging \
        --body-file - \
        --repo "$GH_PROJECT_PATH";
      '
    - git remote add upstream "$GH_PROJECT_URL"
    - git checkout origin/master
    # Merge up to the current commit (not the latest commit)
    - git merge --ff-only "$CI_COMMIT_SHA"
    - git push upstream HEAD:master
  rules:
    # Runs on staging commits
    - if: $CI_COMMIT_BRANCH == 'staging'

release:deployment:
  stage: release
  needs:
    - build:release
  # Don't interrupt deploying job
  interruptible: false
  # Requires mutual exclusion
  resource_group: release:deployment
  environment:
    name: 'production'
    deployment_tier: 'production'
    url: 'https://mainnet.polykey.com'
  script:
    - echo 'Perform service deployment for production'
    - >
      nix-shell --arg ci true --run $'
      npm run deploy -- --env production;
      '
  rules:
    # Runs on master commits
    - if: $CI_COMMIT_BRANCH == 'master'
