name = "polykey-network-dashboard-dev"
main = "worker.ts"
compatibility_date = "2023-03-06"
workers_dev = true
send_metrics = false
routes = [
  "testnet.polykey.com",
  "testnet.polykey.com/*",
]
[site]
  bucket = "./public"

[env.production]
  name = "polykey-network-dashboard"
  routes = [
    "mainnet.polykey.com",
    "mainnet.polykey.com/*",
  ]
  workers_dev = false
